name: Release ZIP

on:
  push:
    tags:
      - 'v*'       
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare release directory
        run: |
          mkdir -p dist
          zip -r "dist/XtremeBS_${{ github.ref_name }}.zip" . -x "*.git*" ".github/*"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/XtremeBS_${{ github.ref_name }}.zip
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
